### ISSUE TITLE
Can't add route outside of spree

### ISSUE THREAD

**Issue by manmartinez** [spree-contrib/spree_sitemap#18]
I can't seem to be able to generate the correct url for a route in my application, my `routes.rb` file looks like this:

```ruby
Rails.application.routes.draw do
  mount Spree::Core::Engine, :at => '/'
  Spree::Core::Engine.routes.draw do
    (some routes here)
  end

  namespace :studio do
    resources :weddings 
  end
end

```

Then in my `sitemap.rb` file I have: 

```ruby
SitemapGenerator::Sitemap.default_host = "http://#{Spree::Store.default.url}"

SitemapGenerator::Sitemap.create do
  add_login
  add_signup
  add_account
  add_taxons
  add_products
  add(studio_wedding_path, changefreq: 'monthly')
end
```

But in the resulting XML I get:

```xml
<url>
    <loc>http://demo.spreecommerce.com/orders/populate?action=show&amp;controller=studio%2Fweddings</loc>
    <lastmod>2014-12-22T20:43:52-06:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
</url>
```

Am I missing something? Why is the `<loc>` node pointing to `/orders/populate`?

**Comment by aishmita-aggarwal** [comment]
Looking into it!

**Comment by aishmita-aggarwal** [comment]
@manmartinez: To add routes outside of spree, please try using routes directly instead of helpers.

I have raised a PR(https://github.com/spree-contrib/spree_sitemap/pull/34) to use main_app(ex: main_app.studio_weddings_path).

**Comment by manmartinez** [comment]
@aishmita-aggarwal Thank you very much for your help!
