### ISSUE TITLE
Limited link number

### ISSUE THREAD

**Issue by vipsolutions** [spree-contrib/spree_sitemap#23]
Hello, i am nob. I have an issue and seems not to be corrected, even in version 2.4.
The number of links is limited to 2582. I have 2790 products and about 15 static pages:

--------------------------------------------------------------
{"count":25,"total_count":2790,"current_page" ...
--------------------------------------------------------------

and the result of generating sitemap is 2582 links:

---------------------------------------------------------------
+ sitemap.xml.gz                                        2582 links /    37.8 KB
Sitemap stats: 2,582 links / 1 sitemaps / 0m11s

Pinging with URL 'http://timepassion.ro/sitemap.xml.gz':
  Successful ping of Google
  Successful ping of Bing
---------------------------------------------------------

This happened on 2.2 version and now on 2.4
It is a bug of this extension or of the sitemap_generator?

**Comment by JDutil** [comment]
There maybe a sitemap_generator setting that needs to be applied or something.  It should be possible to submit multiple sitemaps linked by the main sitemap so if you're hitting a limit you probably need to take advantage of that feature.

**Comment by vipsolutions** [comment]
I limited the number of products, removed some old products and zero priced, now i have about 1943 working products that i pas thought sitemap. I checked sitemap_generator, didn't see any limitations apart from file size. For now is ok, but when I'll pass that number again ... i will try that split. 
Thank you

**Comment by aishmita-aggarwal** [comment]
I am unable to replicate this issue on master.
