### ISSUE TITLE
Update sitemap_generator dependency to v5

### ISSUE THREAD

**Issue by chriscarpenter12** [spree-contrib/spree_sitemap#26]
Can we get an updated gemspec that updates sitemap_generator to the latest version? sitemap_generator v5 has many Fog and S3 improvements.

**Comment by chriscarpenter12** [comment]
I added some pull requests with the changes.

#27 for 2-4-stable, #28 for 3-0-stable and #29 for master

**Comment by alepore** [comment]
thanks!
i'd go only with the master one to not break code on existing stores.
what about using `'sitemap_generator', '~> 5.0.0'` ? just to be safe...

**Comment by chriscarpenter12** [comment]
I included the other branches because I am using 2-4-stable currently. I can continue using my own fork until master creates a new stable branch.

'''~> 5.0.0''' will only bring it up to 5.0.1, but '''~> 5.0''' should keep it up to date until 5.1 if I understand '''~>''' correctly.

I can submit a new commit with the change if that's what you want?

**Comment by alepore** [comment]
`~> 5.0.0` will allow every 5.0.x version but not 5.1+.
`~> 5.0` will allow every 5.x version
as we don't know how external gems are developed imho it's safer to keep `~> 5.0.0` and update that when needed.

yes, please commit to the master PR :)

**Comment by chriscarpenter12** [comment]
Gotcha. Misunderstood that. Thank you. Pushed a new commit and waiting for the CI to finish.

Also at some point whenever the master branch does go into another stable branch people will need to update their ```config/sitemap.rb``` from

```
SitemapGenerator::Sitemap.add_links do
```
to this
```
SitemapGenerator::Sitemap.create do
```
because sitemap_generator deprecated add_links method. Not sure the best way to relay this? Update the README.md?

**Comment by alepore** [comment]
yep, feel free to add a 4 => 5 upgrade note to the README.
thanks!

**Comment by futhr** [comment]
I updated `README.md` with information about this, you welcome to add a PR with improvements if the notes are unclear. As you may read in other spree extensions we avoid adding major changes to stable branches.

**Comment by chriscarpenter12** [comment]
@futhr ```README.md``` looks great. Thanks for updating it for others to see. Makes sense about not breaking stable branches.
